name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy ke Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd ~/forum-api
            git pull origin main
            npm install
            npm run migrate up
            
            # Restart proses jika ada
            # Jika tidak, buatkan proses
            api_pid=$(pm2 pid forum-api)
            if [ -n "${api_pid}" ]; then pm2 restart forum-api; else pm2 start npm --name "forum-api" -- run "start"; fi;
